Rogue reformatting of src/ccpp_hash_table.F90

diff --git a/.github/workflows/fortran-formatting.yaml b/.github/workflows/fortran-formatting.yaml
--- a/.github/workflows/fortran-formatting.yaml
+++ b/.github/workflows/fortran-formatting.yaml
@@ -8,9 +8,11 @@ on:
 env:
   CODEE_VERSION: 2025.4.5
 
-permissions:
-  contents: write
-  pull-requests: write
+# Only needed when fixing formatting automatically, but this only
+# works for pull requests from the same repo, not from a fork
+#permissions:
+#  contents: write
+#  pull-requests: write
 
 jobs:
   format:
@@ -24,7 +26,6 @@ jobs:
           fetch-depth: 0
 
       - name: Get modified Fortran files
-        #id: modified-files
         run: |
           git remote -v show
           git fetch origin ${{ github.base_ref }}
@@ -46,28 +47,33 @@ jobs:
           REFORMATTED_FILES=$(git diff --name-only --diff-filter=d)
           echo "REFORMATTED_FILES=${REFORMATTED_FILES}" >> ${GITHUB_ENV}
 
-      - name: Fail if there are uncommitted changes and the `fix-fortran-format` label is not present
-        if: ${{ env.REFORMATTED_FILES != '' && !contains(github.event.pull_request.labels.*.name, 'fix-fortran-format') }}
+      - name: Fail if there are uncommitted changes
+        if: ${{ env.REFORMATTED_FILES != '' }}
         run: |
-          echo "Formatting issues detected. Run 'codee format' locally or attach label 'fix-fortran-format' to this PR."
+          echo "Formatting issues detected. Run 'codee format' locally or apply the following diff manually:"
+          git diff
           exit 1
 
-#      - name: Fix formatting if label 'fix-fortran-format; is present
-#        if: ${{ env.MODIFIED_FILES != '' && contains(github.event.pull_request.labels.*.name, 'fix-fortran-format') }}
-#        run: |
-#          export PATH="${PWD}/codee-${CODEE_VERSION}-linux-x86_64/bin:${PATH}"
-#          git codee-format --diff origin/${{ github.base_ref }} HEAD
-#          git diff
-
-      - name: Commit changes if the `fix-fortran-format` label is not present
-        if: ${{ env.REFORMATTED_FILES != '' && contains(github.event.pull_request.labels.*.name, 'fix-fortran-format') }}
-        run: |
-          # Push with the github-actions user. More information at:
-          # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
-          git config user.name "github-actions[bot]"
-          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
-          git checkout -b ${{ github.head_ref }}
-          git add ${REFORMATTED_FILES}
-          git commit -m "Apply codee format formatting fixes"
-          echo "DH DEBUG: 'git push --set-upstream origin ${{ github.head_ref }}'"
-          git push --set-upstream origin ${{ github.head_ref }}
+      #- name: Fail if there are uncommitted changes and the `fix-fortran-format` label is not present
+      #  if: ${{ env.REFORMATTED_FILES != '' && !contains(github.event.pull_request.labels.*.name, 'fix-fortran-format') }}
+      #  run: |
+      #    echo "Formatting issues detected. Run 'codee format' locally or attach label 'fix-fortran-format' to this PR."
+      #    exit 1
+      #
+      # This doesn't work if the pull request comes from a fork ...
+      #- name: Commit changes if the `fix-fortran-format` label is not present
+      #  if: ${{ env.REFORMATTED_FILES != '' && contains(github.event.pull_request.labels.*.name, 'fix-fortran-format') }}
+      #  run: |
+      #    # Push with the github-actions user. More information at:
+      #    # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
+      #    git config user.name "github-actions[bot]"
+      #    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+      #    git checkout -b ${{ github.head_ref }}
+      #    git add ${REFORMATTED_FILES}
+      #    git commit -m "Apply codee format formatting fixes"
+      #
+      #    git remote add realsource ${{ github.event.pull_request.head.repo.clone_url }}
+      #    git remote -v show
+      #    git push --set-upstream source ${{ github.head_ref }}
+      #    # If PR comes from the target repository (origin), can do:
+      #    #  git push --set-upstream origin ${{ github.head_ref }}
